// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTuor.Models;

#nullable disable

namespace ProvaWebAPI.Migrations
{
    [DbContext(typeof(WebTuorDbContext))]
    [Migration("20250910164743_InitialModel")]
    partial class InitialModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTuor.Models.Passeio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Passeio");
                });

            modelBuilder.Entity("WebTuor.Models.PontoTuristico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PontoTuristico");
                });

            modelBuilder.Entity("WebTuor.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameFull")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WebTuor.Models.Visita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PasseioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PontoTuristicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PasseioId");

                    b.HasIndex("PontoTuristicoId");

                    b.ToTable("Visita");
                });

            modelBuilder.Entity("WebTuor.Models.Passeio", b =>
                {
                    b.HasOne("WebTuor.Models.User", "Owner")
                        .WithMany("Passeios")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WebTuor.Models.Visita", b =>
                {
                    b.HasOne("WebTuor.Models.Passeio", "Passeio")
                        .WithMany("Visitas")
                        .HasForeignKey("PasseioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebTuor.Models.PontoTuristico", "PontoTuristico")
                        .WithMany("Visitas")
                        .HasForeignKey("PontoTuristicoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Passeio");

                    b.Navigation("PontoTuristico");
                });

            modelBuilder.Entity("WebTuor.Models.Passeio", b =>
                {
                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("WebTuor.Models.PontoTuristico", b =>
                {
                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("WebTuor.Models.User", b =>
                {
                    b.Navigation("Passeios");
                });
#pragma warning restore 612, 618
        }
    }
}
